export const Users = [
  {
    id: 1,
    profilePicture: "/assets/person/1.jpeg",
    username: "John Wick",
  },
  {
    id: 2,
    profilePicture: "/assets/person/2.jpeg",
    username: "John Carter",
  },
  {
    id: 3,
    profilePicture: "/assets/person/3.jpeg",
    username: "Will Smith",
  },
  {
    id: 4,
    profilePicture: "/assets/person/4.jpeg",
    username: "Jason Statham",
  },
  {
    id: 5,
    profilePicture: "/assets/person/5.jpeg",
    username: "Vin Diesel",
  },
  {
    id: 6,
    profilePicture: "/assets/person/6.jpeg",
    username: "Rick Grimes",
  },
  {
    id: 7,
    profilePicture: "/assets/person/7.jpeg",
    username: "Tom Cruize",
  },
  {
    id: 8,
    profilePicture: "/assets/person/8.jpeg",
    username: "Neymar",
  },
  {
    id: 9,
    profilePicture: "/assets/person/9.jpeg",
    username: "Mo Salah",
  },
  {
    id: 10,
    profilePicture: "/assets/person/10.jpeg",
    username: "John Cena",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 22,
    comment: 9,
  },
  {
    id: 3,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/3.jpeg",
    date: "45 mins ago",
    userId: 3,
    like: 45,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 16,
    comment: 9,
  },
  {
    id: 5,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 4,
    comment: 9,
  },
  {
    id: 6,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/6.jpeg",
    date: "10 hours ago",
    userId: 6,
    like: 19,
    comment: 9,
  },
  {
    id: 7,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/7.jpeg",
    date: "16 hours ago",
    userId: 7,
    like: 27,
    comment: 9,
  },
  {
    id: 8,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/8.jpeg",
    date: "20 hours ago",
    userId: 8,
    like: 39,
    comment: 9,
  },
  {
    id: 9,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/post/9.jpeg",
    date: "yesterday",
    userId: 9,
    like: 60,
    comment: 9,
  },
  {
    id: 10,
    photo: "/assets/post/10.jpeg",
    date: "2 days ago",
    userId: 10,
    like: 100,
    comment: 9,
  },
];
